//
// Created by keyz_ on 07/08/2023.
//

#ifndef KNOMI_ALT_STYLE_CSS_H
#define KNOMI_ALT_STYLE_CSS_H

#include <Arduino.h>

const String STYLE_CSS PROGMEM = "html {\n"
                                 "    font-family: Arial, Helvetica, sans-serif; \n"
                                 "    display: inline-block; \n"
                                 "    text-align: center;\n"
                                 "  }\n"
                                 "  \n"
                                 "  h1 {\n"
                                 "    font-size: 1.8rem; \n"
                                 "    color: white;\n"
                                 "  }\n"
                                 "  \n"
                                 "  p { \n"
                                 "    font-size: 1.4rem;\n"
                                 "  }\n"
                                 "  \n"
                                 "  .topnav { \n"
                                 "    overflow: hidden; \n"
                                 "    background-color: #0A1128;\n"
                                 "  }\n"
                                 "  \n"
                                 "  body {  \n"
                                 "    margin: 0;\n"
                                 "  }\n"
                                 "  \n"
                                 "  .content { \n"
                                 "    padding: 5%;\n"
                                 "  }\n"
                                 "  \n"
                                 "  .card-grid { \n"
                                 "    max-width: 800px; \n"
                                 "    margin: 0 auto; \n"
                                 "    display: grid; \n"
                                 "    grid-gap: 2rem; \n"
                                 "    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n"
                                 "  }\n"
                                 "  \n"
                                 "  .card { \n"
                                 "    background-color: white; \n"
                                 "    box-shadow: 2px 2px 12px 1px rgba(140,140,140,.5);\n"
                                 "  }\n"
                                 "  \n"
                                 "  .card-title { \n"
                                 "    font-size: 1.2rem;\n"
                                 "    font-weight: bold;\n"
                                 "    color: #034078\n"
                                 "  }\n"
                                 "  \n"
                                 "  input[type=submit] {\n"
                                 "    border: none;\n"
                                 "    color: #FEFCFB;\n"
                                 "    background-color: #034078;\n"
                                 "    padding: 15px 15px;\n"
                                 "    text-align: center;\n"
                                 "    text-decoration: none;\n"
                                 "    display: inline-block;\n"
                                 "    font-size: 16px;\n"
                                 "    width: 100px;\n"
                                 "    margin-right: 10px;\n"
                                 "    border-radius: 4px;\n"
                                 "    transition-duration: 0.4s;\n"
                                 "    }\n"
                                 "  \n"
                                 "  input[type=submit]:hover {\n"
                                 "    background-color: #1282A2;\n"
                                 "  }\n"
                                 "  \n"
                                 "  input[type=text], input[type=number], select {\n"
                                 "    width: 50%;\n"
                                 "    padding: 12px 20px;\n"
                                 "    margin: 18px;\n"
                                 "    display: inline-block;\n"
                                 "    border: 1px solid #ccc;\n"
                                 "    border-radius: 4px;\n"
                                 "    box-sizing: border-box;\n"
                                 "  }\n"
                                 "  \n"
                                 "  label {\n"
                                 "    font-size: 1.2rem; \n"
                                 "  }\n"
                                 "  .value{\n"
                                 "    font-size: 1.2rem;\n"
                                 "    color: #1282A2;  \n"
                                 "  }\n"
                                 "  .state {\n"
                                 "    font-size: 1.2rem;\n"
                                 "    color: #1282A2;\n"
                                 "  }\n"
                                 "  button {\n"
                                 "    border: none;\n"
                                 "    color: #FEFCFB;\n"
                                 "    padding: 15px 32px;\n"
                                 "    text-align: center;\n"
                                 "    font-size: 16px;\n"
                                 "    width: 100px;\n"
                                 "    border-radius: 4px;\n"
                                 "    transition-duration: 0.4s;\n"
                                 "  }\n"
                                 "  .button-on {\n"
                                 "    background-color: #034078;\n"
                                 "  }\n"
                                 "  .button-on:hover {\n"
                                 "    background-color: #1282A2;\n"
                                 "  }\n"
                                 "  .button-off {\n"
                                 "    background-color: #858585;\n"
                                 "  }\n"
                                 "  .button-off:hover {\n"
                                 "    background-color: #252524;\n"
                                 "  } ";
#endif //KNOMI_ALT_STYLE_CSS_H
