
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: Sleepy1
*
* preset name: Color R5G6B5
* data block size: 16 bit(s), uint16_t
* RLE compression enabled: no
* conversion type: Color, not_used not_used
* split to rows: yes
* bits per pixel: 16
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

#include <Display/Sprites/tImage.h>


class SleepyFace : tImage {
public:
    SleepyFace() : tImage() {}

    uint16_t *getFrame(uint8_t) override;

    uint8_t width = 240;
    uint8_t height = 240;
    uint8_t frames = 2;
};
